goblin time
Cwagne17/vendor-contract-mgmt-client pull request #4
Opened 2022-04-12 21:54 UTC by leeleonard936

delete the txt file

2022-04-15 13:35 UTC, Cwagne17 reviewed
Are you using this PR for your work on the dashboard?

2022-04-15 16:59 UTC, leeleonard936 commented
> Are you using this PR for your work on the dashboard?

Yeah I think so

2022-04-16 14:22 UTC, Cwagne17 commented
Can you delete the txt file that isn't needed.

2022-04-16 15:39 UTC, Cwagne17 reviewed
Re-request once changes have been added

2022-04-16 21:30 UTC, leeleonard936 reviewed
I can't figure out how to get the routing to work if someone could give advice it would be appreciated

2022-04-16 23:08 UTC, Cwagne17 reviewed
Good start👌🏻 are you able to attach a screen shot? Re-request when the dashboard is formatted.

2022-04-16 23:08 UTC, Cwagne17 commented on Leo.txt
> +Hello this is a txt file please delete me
Can we delete this file?

2022-04-16 23:08 UTC, Cwagne17 commented on src/app/app-routing.module.ts
> +    path: 'vendor-dashboard',
Nice routing 👌🏻

2022-04-16 23:08 UTC, Cwagne17 commented on src/app/app.component.ts
> +    console.log('Called ngOnInit method');
Can we remove the console logs?

2022-04-16 23:08 UTC, Cwagne17 commented on src/app/app.module.ts
> +const routes: Routes = [
Do we need this const declared here?

2022-04-16 23:08 UTC, Cwagne17 commented on src/app/pages/vendor-dashboard/vendor-dashboard.component.ts
> +    console.log('Called ngOnInit method');
Should the options be set in the ngoninit or constructor? I'm not sure

2022-04-16 23:08 UTC, Cwagne17 commented on src/app/pages/vendor-dashboard/vendor-dashboard.component.ts
> +    console.log('Called ngOnInit method');
As long as it works 👍🏻

2022-04-16 23:08 UTC, Cwagne17 commented on src/styles.scss
> +html, body { height: 100%; }
We can add global styling variables for colors and such. That way they can be imported and used throughout our app

2022-04-16 23:09 UTC, Cwagne17 commented
> I can't figure out how to get the routing to work if someone could give advice it would be appreciated

Could you still not get it to work?

2022-04-28 16:21 UTC, Cwagne17 commented on src/app/pages/vendor-dashboard/vendor-dashboard.component.html
>    <input matInput placeholder="Search">
Are you able to get the search text to apply to a variable in the component.ts file? If not don't worry about it. I can connect it up real quick when I connect the routes Robby is adding.

2022-04-28 16:23 UTC, Cwagne17 requested changes
Remove some commented out code, other then that looks good. Will just need to merge Liam and Bryan's content then merge in to main.

2022-04-28 16:23 UTC, Cwagne17 commented on src/app/pages/vendor-dashboard/vendor-dashboard.component.html
> +    <!--<ng-container matColumnDef="butt">
We can delete this since we don't need it

2022-04-28 16:23 UTC, Cwagne17 commented on src/app/pages/vendor-dashboard/vendor-dashboard.component.ts
> +/*    first_name: string;
How come these are commented out?

2022-04-28 16:23 UTC, Cwagne17 commented on src/app/pages/vendor-dashboard/vendor-dashboard.component.ts
> +  displayedColumns: string[] = ['vendor_name', 'contact_phone_number', 'status', 'work_id'/*, 'butt'*/];
We can remove the commented out section

2022-04-28 16:23 UTC, Cwagne17 commented on src/app/pages/vendor-dashboard/vendor-dashboard.component.ts
> +    //dialogRef2.updatePosition()
lets remove the commented out code.

2022-04-28 16:23 UTC, Cwagne17 commented on src/app/pages/vendor-dashboard/vendor-dashboard.component.ts
>    //openFilter(): void {
lets remove the commented out code

2022-04-28 16:40 UTC, merged